"""Point .env at one of the profiles in env/.

Switching environments used to mean copying a file over .env by hand, which is
how fifteen dated .env.* snapshots accumulated at the repo root - and how the
stale one ended up carrying the most obvious name. The profiles in env/ are the
source of truth now; .env is generated from them and is safe to overwrite.

    python tools/use_env.py            # report what .env currently points at
    python tools/use_env.py uat        # switch
    python tools/use_env.py qa --dry-run

Jenkins is unaffected: it drops a Secret file credential straight to .env and
deletes it in cleanup, and never consults env/.
"""

import argparse
import datetime as dt
import os
import re
import shutil
import sys
from pathlib import Path
from urllib.parse import urlparse

PROJECT_ROOT = Path(__file__).resolve().parents[1]
PROFILE_DIR = PROJECT_ROOT / "env"
DOTENV = PROJECT_ROOT / ".env"

GENERATED_BANNER = "# GENERATED BY tools/use_env.py - DO NOT EDIT"


def available_profiles():
    if not PROFILE_DIR.is_dir():
        return []
    return sorted(path.stem for path in PROFILE_DIR.glob("*.env"))


def read_key(text, key):
    match = re.search(rf"^{re.escape(key)}=(.*)$", text, flags=re.MULTILINE)
    return match.group(1).strip().strip('"').strip("'") if match else None


def describe(path):
    """Profile name and host a given env file resolves to."""
    if not path.exists():
        return None, None
    text = path.read_text(encoding="utf-8")
    profile = read_key(text, "CBSE_ENV_PROFILE")
    base_url = read_key(text, "CBSE_BASE_URL") or ""
    return profile, urlparse(base_url).hostname


def report():
    profile, host = describe(DOTENV)
    if host is None:
        print(".env is missing or has no CBSE_BASE_URL.")
        return 1
    label = profile or "(unnamed - predates tools/use_env.py)"
    print(f".env -> profile={label}  host={host}")
    print(f"profiles available: {', '.join(available_profiles()) or 'none'}")
    return 0


def switch(name, dry_run=False):
    source = PROFILE_DIR / f"{name}.env"
    if not source.exists():
        print(f"No profile {name!r}. Available: {', '.join(available_profiles()) or 'none'}", file=sys.stderr)
        return 2

    # A profile whose declared host disagrees with its own CBSE_BASE_URL would
    # trip conftest's guard on the very next run; say so here instead.
    text = source.read_text(encoding="utf-8")
    expected_host = read_key(text, "CBSE_ENV_EXPECTED_HOST")
    actual_host = urlparse(read_key(text, "CBSE_BASE_URL") or "").hostname
    if expected_host and actual_host and expected_host != actual_host:
        print(
            f"Profile {name!r} is inconsistent: CBSE_ENV_EXPECTED_HOST={expected_host} "
            f"but CBSE_BASE_URL resolves to {actual_host}. Fix {source} first.",
            file=sys.stderr,
        )
        return 3

    current_profile, current_host = describe(DOTENV)
    if dry_run:
        print(f"would switch .env: {current_host} -> {actual_host} (profile {name})")
        return 0

    # Keep one rolling copy of whatever .env held, in case it carried a local
    # edit that was never folded back into its profile. One, not a dated chain:
    # the dated chain is what this script exists to end.
    if DOTENV.exists():
        shutil.copy2(DOTENV, PROFILE_DIR / "_archive" / "previous.env")

    stamp = dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    header = (
        f"{GENERATED_BANNER}\n"
        f"# Written from env/{name}.env at {stamp}.\n"
        f"# Edit env/{name}.env and re-run `python tools/use_env.py {name}`.\n\n"
    )
    DOTENV.write_text(header + text, encoding="utf-8")
    was = current_host or "nothing"
    print(f"switched .env: {was} -> {actual_host} (profile {name})")
    print(f"previous .env saved to env/_archive/previous.env")
    return 0


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("profile", nargs="?", help="profile to activate (omit to report current)")
    parser.add_argument("--dry-run", action="store_true", help="show the switch without writing .env")
    args = parser.parse_args()

    if not args.profile:
        return report()
    return switch(args.profile, dry_run=args.dry_run)


if __name__ == "__main__":
    raise SystemExit(main())
